LEVEL = ../../../..
LIBRARYNAME = HPPTraceAnalysis
LOADABLE_MODULE = 1
USEDLIBS = pathTracing.a profiler.a

include $(LEVEL)/Makefile.common
#CXXFLAGS += -std=c++0x -g -fPIC
CXXFLAGS += -std=c++0x -g -fPIC -DCPU_PROFILE

